/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IMaterialSymbolsBackspaceOutlineRounded: typeof import('~icons/material-symbols/backspace-outline-rounded')['default']
    IMaterialSymbolsCancelOutlineRounded: typeof import('~icons/material-symbols/cancel-outline-rounded')['default']
    IMaterialSymbolsCheckCircleOutlineRounded: typeof import('~icons/material-symbols/check-circle-outline-rounded')['default']
    IMaterialSymbolsCheckRounded: typeof import('~icons/material-symbols/check-rounded')['default']
    IMaterialSymbolsProgressActivity: typeof import('~icons/material-symbols/progress-activity')['default']
    UiButton: typeof import('./components/UiButton.vue')['default']
    UiEmojiKeyboard: typeof import('./components/UiEmojiKeyboard.vue')['default']
    UiEmojiKeyboardButton: typeof import('./components/UiEmojiKeyboardButton.vue')['default']
    UiEmojis: typeof import('./components/UiEmojis.vue')['default']
    UiInput: typeof import('./components/UiInput.vue')['default']
    UiOverlay: typeof import('./components/UiOverlay.vue')['default']
  }
}
